SELECT	*
FROM	TB_UNIQUE_DEV_NODE
WHERE	C_PERMISSION <> '';

SELECT	A.DEV_NODE, 		
		group_concat(DISTINCT IF(A.N_PERMISSION = '',NULL,A.N_PERMISSION) ORDER BY 1 DESC) AS N_PERMISSION, 
		group_concat(DISTINCT IF(A.N_USER = '',NULL,A.N_USER) ORDER BY 1 ASC) AS N_USER, 
		group_concat(DISTINCT IF(A.N_GROUP = '',NULL,A.N_GROUP) ORDER BY 1 ASC) AS N_GROUP,
		group_concat(DISTINCT IF(A.C_PERMISSION = '',NULL,A.C_PERMISSION) ORDER BY 1 DESC) AS C_PERMISSION, 
		group_concat(DISTINCT IF(A.C_USER = '',NULL,A.C_USER) ORDER BY 1 ASC) AS C_USER, 
		group_concat(DISTINCT IF(A.C_GROUP = '',NULL,A.C_GROUP) ORDER BY 1 ASC) AS C_GROUP
FROM	TB_UEVENTD_CMP_RESULT AS A
GROUP BY A.DEV_NODE HAVING (max(DISTINCT A.C_PERMISSION) <> MAX(DISTINCT A.N_PERMISSION))
#GROUP BY A.DEV_NODE

;
CREATE TABLE TB_UNIQUE_DEV_NODE AS
SELECT	A.DEV_NODE, 
		group_concat(DISTINCT IF(A.N_PERMISSION = '',NULL,A.N_PERMISSION) ORDER BY 1 DESC) AS N_PERMISSION, 
		group_concat(DISTINCT IF(A.N_USER = '',NULL,A.N_USER) ORDER BY 1 ASC) AS N_USER, 
		group_concat(DISTINCT IF(A.N_GROUP = '',NULL,A.N_GROUP) ORDER BY 1 ASC) AS N_GROUP,
		group_concat(DISTINCT IF(A.C_PERMISSION = '',NULL,A.C_PERMISSION) ORDER BY 1 DESC) AS C_PERMISSION, 
		group_concat(DISTINCT IF(A.C_USER = '',NULL,A.C_USER) ORDER BY 1 ASC) AS C_USER, 
		group_concat(DISTINCT IF(A.C_GROUP = '',NULL,A.C_GROUP) ORDER BY 1 ASC) AS C_GROUP,
		NULL AS DESCRIPTION,
		NULL AS DEV_TYPE,
		NULL AS LINK1,
		NULL AS LINK2,
		NULL AS LINK3,
		NULL AS LINK4,
		NULL AS LINK5
FROM	TB_UEVENTD_CMP_RESULT AS A
GROUP BY A.DEV_NODE

;
