
#GET DEVICE'S DEV_NODE LIST WHICH INCLUDES SPECIFIC VULNERABILITIES
SELECT 	B.DEVICE_MODEL,
		B.DEVICE_NAME,
		B.OS_VERSION,
		B.REGION,
		A.DEV_NODE,
		A.C_PERMISSION,
		A.C_USER,
		A.C_GROUP,
#		A.F_ONLY_IN_CUSTOM,
#		A.F_PERMISSION_ABUSE,
		A.FW_FILE_NAME

FROM 	linuxdroid.TB_UEVENTD_CMP_RESULT AS A
		LEFT OUTER JOIN
		linuxdroid.TB_RAW_PHONE_FW AS B
#		linuxdroid.TB_RAW_DOWNLOADED_FW AS B
		ON (A.FW_FILE_NAME = LEFT(B.FILE_NAME,LENGTH(B.FILE_NAME)-4))
WHERE 	A.F_ONLY_IN_CUSTOM = 1 
		AND A.F_PERMISSION_ABUSE = 1
		AND A.FW_FILE_NAME IN
							(
							SELECT 	A.FW_FILE_NAME

							FROM 	linuxdroid.TB_UEVENTD_CMP_RESULT AS A
									LEFT OUTER JOIN
									linuxdroid.TB_RAW_PHONE_FW AS B
							#		linuxdroid.TB_RAW_DOWNLOADED_FW AS B
									ON (A.FW_FILE_NAME = LEFT(B.FILE_NAME,LENGTH(B.FILE_NAME)-4))
							WHERE 	A.F_ONLY_IN_CUSTOM = 1 
									AND A.F_PERMISSION_ABUSE = 1
									AND A.DEV_NODE LIKE '%fb%'
							)

;


#GET LIST OF DEVICES WHICH SETS FRAMEBUFFER TO PUBLIC
SELECT 	B.DEVICE_MODEL,
		B.DEVICE_NAME,
		B.OS_VERSION,
		B.REGION,
		A.DEV_NODE,
		A.C_PERMISSION,
		A.C_USER,
		A.C_GROUP,
		A.F_ONLY_IN_CUSTOM,
		A.F_PERMISSION_ABUSE,
		A.FW_FILE_NAME

FROM 	linuxdroid.TB_UEVENTD_CMP_RESULT AS A
		LEFT OUTER JOIN
		linuxdroid.TB_RAW_PHONE_FW AS B
#		linuxdroid.TB_RAW_DOWNLOADED_FW AS B
		ON (A.FW_FILE_NAME = LEFT(B.FILE_NAME,LENGTH(B.FILE_NAME)-4))
WHERE 	#A.F_ONLY_IN_CUSTOM = 1 
		#AND A.F_PERMISSION_ABUSE = 1
		#AND 
		A.DEV_NODE LIKE '%fb%'

;

