#DEVICE COMPARISON QUERY
SELECT	CL.FW_FILE_NAME,
		CL.OS_VERSION,
		CL.DEV_NODE,
		NF.PERMISSION AS N_PERMISSION,
		NF.USER AS N_USER,
		NF.GROUP AS N_GROUP,
		CF.PERMISSION AS C_PERMISSION,
		CF.USER AS C_USER,
		CF.GROUP AS C_GROUP
FROM
(
SELECT DISTINCT L.FW_FILE_NAME, L.OS_VERSION, L.DEV_NODE
FROM	(
		(
		SELECT	A.FW_FILE_NAME, A.OS_VERSION, B.DEV_NODE
		FROM	(
				SELECT	DISTINCT FW_FILE_NAME, OS_VERSION
				FROM	TB_CUSTOM_UEVENTD
				) AS A
				INNER JOIN
				TB_NEXUS_UEVENTD AS B
				ON (A.OS_VERSION = B.OS_VERSION)
		)
		UNION all
		(
		SELECT	C.FW_FILE_NAME, C.OS_VERSION, C.DEV_NODE
		FROM	TB_CUSTOM_UEVENTD AS C
		)
		) AS L
#WHERE	L.FW_FILE_NAME = '3IE-S7710XXAMD2-20130426165153'
ORDER BY L.FW_FILE_NAME, L.DEV_NODE
) AS CL
LEFT OUTER JOIN 
TB_NEXUS_UEVENTD AS NF
ON (CL.OS_VERSION = NF.OS_VERSION AND CL.DEV_NODE = NF.DEV_NODE)
LEFT OUTER JOIN
TB_CUSTOM_UEVENTD AS CF
ON (CL.FW_FILE_NAME = CF.FW_FILE_NAME AND CL.DEV_NODE = CF.DEV_NODE)
;
