SELECT	A.REGION, A.DEVICE_NAME, A.DEVICE_MODEL, A.OS_VERSION, A.FILE_NAME, A.DOWNLOADED_YN, A.EXTRACTED_YN
FROM	TB_RAW_PHONE_FW AS A
WHERE	A.OS_VERSION LIKE '4%'
		AND IFNULL(A.DOWNLOADED_YN, 0) = 1
		#AND IFNULL(A.EXTRACTED_YN, 0) = 0
		AND A.DEVICE_MODEL IN ('SPH-D710', 'SPH-L300')
		AND A.REGION IN ('ATTAt&t'
,'USCU.s. cellular'
,'XABUsa'
,'VZWVerizon wireless'
,'TMBUsa (t-mobile)'
,'XASSprint (usa)'
,'SPRU.s. (spint)')
ORDER BY A.REGION, A.DEVICE_NAME, A.OS_VERSION ASC
;

#GET DISTINCT DEVICE LIST
SELECT	DISTINCT A.REGION
FROM	TB_RAW_PHONE_FW AS A
WHERE	UPPER(A.DEVICE_NAME) LIKE '%USA%'
ORDER BY A.REGION ASC
;

SELECT	*
FROM	TB_RAW_PHONE_FW
WHERE	DEVICE_MODEL = 'SGH-T999L'
;