
UPDATE 	TB_RAW_PHONE_FW AS T
SET		T.DOWNLOADED_YN = 1
WHERE	T.FILE_NAME IN (
						SELECT	A.FILE_NAME
						FROM	TB_RAW_DOWNLOADED_FW AS A
								
						)

;


UPDATE 	TB_RAW_PHONE_FW AS T
SET		T.EXTRACTED_YN = 1
WHERE	LEFT(T.FILE_NAME,LENGTH(T.FILE_NAME)-4) IN (
						SELECT	DISTINCT FW_FILE_NAME
						FROM	TB_UEVENTD_CMP_RESULT								
						)

;

SELECT	B.*
FROM	TB_RAW_PHONE_FW AS B
		INNER JOIN 
		TB_RAW_DOWNLOADED_FW AS A
		ON (A.FILE_NAME = B.FILE_NAME)

;

SELECT	A.*
FROM	TB_RAW_DOWNLOADED_FW AS A 
;


SELECT	DISTINCT FW_FILE_NAME
FROM	TB_UEVENTD_CMP_RESULT;